web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    env_file: .env
    volumes:
        - ./:/var/www
    links:
        - db
db:
    image: postgres
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    # If you don't want to use default 'artisan serve' command, edit and uncomment the line below.
    # command: php -S 0.0.0.0:80 -t public public/index.php